require "rails_helper"

RSpec.describe CloseCompletedPurchaseOrdersJob, type: :job do
  # Pin supplier_id explicitly so these records never consume the FactoryBot
  # `supplier_id` sequence — the OpenAPI doc example (generated by the full
  # request spec suite) captures live sequence values, and drawing from it here
  # would shift those example values and trip the doc-drift CI check.
  describe "#perform" do
    it "closes a RECEIVED PO" do
      po = create(:supplier_purchase_order, :received, supplier_id: "VENDOR-JOB-1")

      described_class.new.perform

      expect(po.reload.status).to eq("CLOSED")
    end

    it "leaves an OPEN PO untouched" do
      po = create(:supplier_purchase_order, :open, supplier_id: "VENDOR-JOB-2")

      described_class.new.perform

      expect(po.reload.status).to eq("OPEN")
    end

    it "leaves a PARTIALLY_RECEIVED PO untouched" do
      po = create(:supplier_purchase_order, :partially_received, supplier_id: "VENDOR-JOB-3")

      described_class.new.perform

      expect(po.reload.status).to eq("PARTIALLY_RECEIVED")
    end

    it "does not affect an already-CLOSED PO" do
      po = create(:supplier_purchase_order, :closed, supplier_id: "VENDOR-JOB-4")

      described_class.new.perform

      expect(po.reload.status).to eq("CLOSED")
    end

    it "returns the number of POs it closed" do
      create(:supplier_purchase_order, :received, supplier_id: "VENDOR-JOB-5")
      create(:supplier_purchase_order, :received, supplier_id: "VENDOR-JOB-6")
      create(:supplier_purchase_order, :open, supplier_id: "VENDOR-JOB-7")

      expect(described_class.new.perform).to eq(2)
    end

    it "is idempotent: running twice does not error or double-act" do
      po = create(:supplier_purchase_order, :received, supplier_id: "VENDOR-JOB-8")

      described_class.new.perform
      second_run = described_class.new.perform

      expect(po.reload.status).to eq("CLOSED")
      expect(second_run).to eq(0)
    end

    it "can be enqueued via Active Job / Solid Queue" do
      expect { described_class.perform_later }
        .to have_enqueued_job(described_class)
    end
  end
end
